#!/bin/bash
# Setup script for the Claude Code cloud environment (claude.ai/code → environment settings).
#
# This file is the reference copy: paste its contents into the environment's "Setup script"
# field and keep the two in sync. It provisions the machine only (JDK, Android SDK, Spec Kit
# CLI); the repository-level Spec Kit tooling is generated by scripts/cloud-speckit-init.sh.
#
# Environment variables to set in the environment:
#   ANDROID_HOME=/opt/android-sdk
#   ANDROID_SDK_ROOT=/opt/android-sdk
#
# Network allowlist, on top of "default list of common package managers":
#   dl.google.com, downloads.gradle.org (plus maven.google.com, plugins.gradle.org,
#   services.gradle.org, github.com, which the default list already has), and
#   astral.sh for the uv installer.
set -euo pipefail

ANDROID_HOME="${ANDROID_HOME:-/opt/android-sdk}"
SDK_TOOLS_ZIP="commandlinetools-linux-16111833_latest.zip"   # cmdline-tools 23.0, 2026-10
SPEC_KIT_VERSION="v1.0.12"                                   # keep equal to the local `specify --version`
SUDO=""; [ "$(id -u)" -ne 0 ] && SUDO="sudo"

# JDK 17+ and unzip
PKGS=()
java -version 2>&1 | grep -qE 'version "(1[7-9]|[2-9][0-9])' || PKGS+=(openjdk-17-jdk-headless)
command -v unzip >/dev/null || PKGS+=(unzip)
if [ ${#PKGS[@]} -gt 0 ]; then
  $SUDO apt-get update -qq
  $SUDO apt-get install -y -qq "${PKGS[@]}"
fi

# Android command-line tools
SDKM="$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager"
if [ ! -x "$SDKM" ]; then
  $SUDO mkdir -p "$ANDROID_HOME/cmdline-tools"
  $SUDO chown -R "$(id -u):$(id -g)" "$ANDROID_HOME"
  curl -fsSL -o /tmp/clt.zip "https://dl.google.com/android/repository/$SDK_TOOLS_ZIP"
  unzip -q /tmp/clt.zip -d /tmp/clt
  mv /tmp/clt/cmdline-tools "$ANDROID_HOME/cmdline-tools/latest"
  rm -rf /tmp/clt /tmp/clt.zip
fi

# Licences + base packages; Gradle downloads any other SDK level it needs.
# `|| true`: `yes` is killed by SIGPIPE when sdkmanager stops reading.
yes | "$SDKM" --licenses >/dev/null || true
"$SDKM" --install "platform-tools" "platforms;android-36" "build-tools;36.0.0" >/dev/null

# Spec Kit CLI (via uv)
export PATH="$HOME/.local/bin:$PATH"
if ! command -v uv >/dev/null; then
  curl -LsSf https://astral.sh/uv/install.sh | sh
fi
if ! command -v specify >/dev/null; then
  uv tool install specify-cli --from "git+https://github.com/github/spec-kit.git@$SPEC_KIT_VERSION"
fi

java -version
"$SDKM" --list_installed
specify --version || true
